apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello
spec:
  selector:
    app: hello-world
  ports:
    - name: hello-application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
